#   Makefile generated by Keil2GCC convertor.
#     @ 2016 Ondrej Sterba, osterba@inbox.com
# 
# GENERATED MAKEFILE IS PROVIDED "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.
#/

PROJECT = Crazepony

CC	= arm-none-eabi-gcc
AS	= arm-none-eabi-as
LD	= arm-none-eabi-g++
CP	= arm-none-eabi-objcopy
OS	= arm-none-eabi-size
OD	= arm-none-eabi-objdump
OPENOCD	= openocd

VECTOR	= StartUp/startup_stm32f10x_md.s

LDFLAGS  = -mcpu=cortex-m3 -mthumb -mfloat-abi=soft -lnosys -Wl,--gc-sections -Wl,-Map,$(PROJECT).map

INC = -I.\
	  -IControl/C\
      -IControl/H\
      -IHardWareDriver/C\
      -IHardWareDriver/H\
      -ILib/inc\
      -IStartUp\
      -IUser_Src\

SRC = $(VECTOR) \
      Control/C/Control.c\
      Control/C/ReceiveData.c\
      HardWareDriver/C/BT.c\
      HardWareDriver/C/Battery.c\
      HardWareDriver/C/DMP.c\
      HardWareDriver/C/HMC5883L.c\
      HardWareDriver/C/IIC.c\
      HardWareDriver/C/Led.c\
      HardWareDriver/C/MPU6050.c\
      HardWareDriver/C/MS5611.c\
      HardWareDriver/C/Moto.c\
      HardWareDriver/C/NRF24L01.c\
      HardWareDriver/C/SPI.c\
      HardWareDriver/C/Tim.c\
      HardWareDriver/C/UART1.c\
      HardWareDriver/C/delay.c\
      HardWareDriver/C/stmflash.c\
      Lib/src/misc.c\
      Lib/src/stm32f10x_gpio.c\
      Lib/src/stm32f10x_i2c.c\
      Lib/src/stm32f10x_pwr.c\
      Lib/src/stm32f10x_rcc.c\
      Lib/src/stm32f10x_spi.c\
      Lib/src/stm32f10x_tim.c\
      Lib/src/stm32f10x_usart.c\
      StartUp/core_cm3.c\
      StartUp/system_stm32f10x.c\
      User_Src/Altitude.c\
      User_Src/CommApp.c\
      User_Src/CommPc.c\
      User_Src/ConfigTable.c\
      User_Src/FailSafe.c\
      User_Src/IMU.c\
      User_Src/IMUSO3.c\
      User_Src/Sys_Fun.c\
      User_Src/filter.c\
      User_Src/main.c\
      User_Src/stm32f10x_it.c\

#  C source files
CFILES = $(filter %.c, $(SRC))
#  Assembly source files
ASMFILES = $(filter %.s, $(SRC))

# Object files
COBJ = $(CFILES:.c=.o)
SOBJ = $(ASMFILES:.s=.o)
OBJ  = $(COBJ) $(SOBJ)

# Compile thumb for cortex-m3 with debug info
CFLAGS  = -g -mthumb -DUSE_STDPERIPH_DRIVER -DSTM32F10X_MD -DSTM32F10X_MD -mcpu=cortex-m3 -mfloat-abi=soft -Og -fpack-struct -fdata-sections -ffunction-sections -std=c99
ASFLAGS = -g -mthumb -mcpu=cortex-m3


all: $(SRC) $(PROJECT).elf $(PROJECT).hex $(PROJECT).bin

$(PROJECT).bin: $(PROJECT).elf
	@$(CP) -O binary $(PROJECT).elf $@

$(PROJECT).hex: $(PROJECT).elf
	@$(CP) -O ihex $(PROJECT).elf $@

$(PROJECT).elf: $(OBJ)
	@echo Linking
	@$(LD) $(LDFLAGS) $(OBJ) -o $@
	@$(OS) -t $(PROJECT).elf

$(COBJ): %.o: %.c
	@echo $<
	@$(CC) -c $(INC) $(CFLAGS) $< -o $@

$(SOBJ): %.o: %.s
	@echo $<
	@$(AS) -c $(ASFLAGS) $< -o $@

clean:
	@rm -f $(PROJECT).elf $(PROJECT).bin $(PROJECT).map $(PROJECT).hex $(PROJECT).lss $(OBJ)

install: $(PROJECT).bin
	JLink.exe -device STM32F103T8 -CommanderScript ./flash.jlink
